In [ ]:
import numpy as np

In [13]:
# Array 1D

d1 = np.array([1,2,3])
print(d1)

[1 2 3]


In [14]:
d1.shape

(3,)

In [16]:
d1.ndim

1

In [17]:
d1.dtype

dtype('int32')

In [18]:
d2 = np.array([[1,2,3], [4,5,6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [19]:
d2.shape

(2, 3)

In [20]:
d2.ndim

2

In [21]:
d2.dtype

dtype('int32')

In [29]:
d3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
d3.shape

(2, 2, 2)

In [34]:
d3.ndim

3

In [33]:
d3.dtype

dtype('int32')