In [1]:
import numpy as np

In [7]:
a = np.array([2,3,4])#[2,3,4] Também funciona com arrays fora do formato do numpy
b = np.array([2,3,4])

In [8]:
c= np.add(a,b)
print(c)

[4 6 8]


In [9]:
a2d = np.array([[2,3,4,5], [6,7,8,9]])
print(a2d)

[[2 3 4 5]
 [6 7 8 9]]


In [14]:
#array[row,column] ou[axis0,axis1]

a2d[1,2]

8

In [18]:
a2d[-1,-2]

8

In [19]:
a2d[0,:]

array([2, 3, 4, 5])

In [21]:
a2d[:, 1]

array([3, 7])